### ISSUE TITLE
Sketch question

### ISSUE THREAD

**Issue by dennisdebel** [daniel1111/ArduinoCdPlayer#1]
Hi Daniel, 
Super nice project, did you use the sketch provided in the Original folder as you mentioned? Since you are using a pca9555 instead of the multiplexers used in the original I wonder if something needs to be changed. Going to go through the bom now and try to built one myself!

**Comment by daniel1111** [comment]
Hi dennisdebel, 

No, that's the code mines based of off, but the actual code I used is under sketchbook/cd2/ (with the libraries it depends on in sketchbook/libraries/.

You can either copy the 3 libraries to your Arduino folder, then load the "cd2.ino" sketch, or change your arduino sketchbook folder to the sketchbook in this repo (avoids having to install globally).

**Comment by dennisdebel** [comment]
Great! Thanks! I will prolly come back with more questions once I have the boards in etc.

**Comment by daniel1111** [comment]
oh, if you are seriously thinking about building this, have you read the "What doesn't work / issues:" section here:
https://hackaday.io/project/176545-arduino-cd-player

There a few kinda significant issues noted atm

**Comment by dennisdebel** [comment]
Yes I read them! Seems doable? Only route on trace? I don't need spdif or
display etc. just wanna built it and see how it performs and what extra
features I could add to it :)

**Comment by daniel1111** [comment]
Oh totally, very minor stuff, just checking you were aware, that's all :)
